### ISSUE TITLE
Missing Travis test

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/MarlinDev#10]
@boelle 
Please activate the Travis test.

**Comment by boelle** [comment]
i dont know how

Den mandag den 3. august 2015 skrev AnHardt <notifications@github.com>:

**Comment by boelle** [comment]
found out

we need a travis ylm file but i guess its allready there

will enable during today

Den mandag den 3. august 2015 skrev Bo Herrmannsen <bo.herrmannsen@gmail.com

**Comment by boelle** [comment]
morning :-D

should be done now

**Comment by boelle** [comment]
hmm... instructions says:

"Trigger your first build with a git push"

now sure how and if i can do that from the web interface

**Comment by AnHardt** [comment]
Thanks a lot.
The next PR will show if it works.

**Comment by boelle** [comment]
make a PR with a txt file saying marlin is awesome firmware ?

2015-08-03 9:26 GMT+02:00 AnHardt <notifications@github.com>:

**Comment by AnHardt** [comment]
No. Will do something more meaningful this morning.

**Comment by boelle** [comment]
closing this one as the first PR after travis was enabled now runs
