### ISSUE TITLE
Hangout -- Saturday August 29 UTC 2000 

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/MarlinDev#107]
Name  | Summer Time Zone
------------ | -------------
@thinkyhead    |  UTC-7
@Wackerbarth  |   UTC-5
@Jnesselr    |    UTC-6
@clefranc     |   UTC-4
@alexborro    |   UTC-3
@fmalpartida   |  UTC+1
@AnHardt     |    UTC+1
@Wurstnase    |   UTC+1
@CONSULitAS   |   UTC+1
@paclema     |    UTC+1
@boelle    |      UTC+1
@emartinez167   |  UTC+8
@ntoff    |       UTC+10
@Roxy-3DPrintBoard  |   UTC-5

[The "Official" UTC Clock](http://www.timeanddate.com/time/aboututc.html)
[Link to the Hangout](https://plus.google.com/hangouts/_/gxn3wrea5gdhoo223yimsiforia)

It's been two weeks. Time for another session.
I hope that we might get some better turnout.

It's time that we put out a Release Candidate.

Please provide input about what we need to discuss.
[Link to Google Document listing discussion topics (Week 35)](https://docs.google.com/document/d/1GmKjDVOKLj6f6s76ZL99LvCPOwy_PkYK57M88Q2oNdM/edit?usp=sharing)

**Comment by fmalpartida** [comment]
Cool, tomorrow evening! Forget the previous comment on the other issue.

**Comment by fmalpartida** [comment]
Well Saturday.

**Comment by Jnesselr** [comment]
I'm UTC-6 now btw.

**Comment by Wackerbarth** [comment]
@Jnesselr -- Colorado? I thought you were in Arkansas (Central Daylight Time, like myself)

**Comment by Jnesselr** [comment]
I moved to Colorado a couple of months ago.

**Comment by Wackerbarth** [comment]
OK, fixed

**Comment by Jnesselr** [comment]
Thank you very much

**Comment by thinkyhead** [comment]
Definitely time to get out RC1 and start getting feedback (especially on `G29`) from the wider community. And we might take time to look at some of the pending PRs and decide where they stand.

**Comment by Wackerbarth** [comment]
I hope that any "almost ready to be included" items can be upgraded and included before Saturday.

**Comment by scalez** [comment]
@thinkyhead @jbrazio have the hangout meetings stopped? I would still be interested in attending them.

**Comment by jbrazio** [comment]
@scalez they have been stopped for a while. It may be something we restart once the GA is out if enough interest is shown by the community.

But to be honest, I like the openness of Github, everything we discuss is widely open to be read and commented by the community, I do prefer this rather than a "back alley talk between a few".
