### ISSUE TITLE
Does Marlin still need better delta calibration options ?

### ISSUE THREAD

**Issue by BuzzBumbleBee** [MarlinFirmware/MarlinDev#117]
Please see the last few commits here :- 

https://github.com/BuzzBumbleBee/Marlin/commits/Delta-Trim

These would allow massive improvements to the prints from most home made deltas (tiny differences in things like rod lengths can have massive effects on the print sizes)

*** Sorry for the code being out of date, if this is still wanted im happy to port/rebase into current dev ***

**Comment by Wackerbarth** [comment]
Of course we need better calibration options.  But the infrastructure that will be in Marlin 1.1 is not the way we need to accomplish this. This feature needs to be a part of Marlin 1.2.
