### ISSUE TITLE
a little change needed in configuration.h

### ISSUE THREAD

**Issue by taalabash** [MarlinFirmware/MarlinDev#130]
in z probe options in delta configurations i think `HOMING_FEEDRATE_X` should be `homing_feedrate[Z_AXIS]` because `HOMING_FEEDRATE_X` is giving compile error `HOMING_FEEDRATE_X was not declared in this scope`

**Comment by thinkyhead** [comment]
@taalabash Good catch! I'm not sure how that came about. The Kossel Pro configuration has `HOMING_FEEDRATE_[XYZ]` (and it doesn't matter that they come later in the file). But the other delta configurations lack it somehow. I will patch this right away!

**Comment by thinkyhead** [comment]
I've added a fix to #128 which fixes other similar things in Delta configs.

**Comment by taalabash** [comment]
Thank you for this really fast fix!!  :)
