### ISSUE TITLE
FORK 5 Axis....

### ISSUE THREAD

**Issue by D9ve** [MarlinFirmware/MarlinDev#158]
Hello to all, 

I know this really isn't a issue, but... I am currently looking into the marlin firmware to see it it is possible to customise this for a 5 dof/axis 3D printer, I will also develop a simple slicer as well an integrated 3D scanner.

Primarily the software I will be using is MACH3, RHINO, and atmel studio 6.2 for development

So really I am asking do you think customising this code for 5 axis is possible? 

I am using ramps 1.4, with only a single extruder, this leaves me with 2 stepper drivers available, mind one is on the AUX pins 23 25 29!

What do you think? should I be placing my ideas and comments on another forum? Any info would be greatly appreciated.

**Comment by Dark-Guan** [comment]
A 5 dof/axis 3D printer mean there is 6 motors . Marlin can aford it

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3856
