### ISSUE TITLE
Option to Shutdown Power Supply on MAXTEMP

### ISSUE THREAD

**Issue by 1-23** [MarlinFirmware/MarlinDev#173]
It would be an excellent safety feature to have Marlin shutdown an external power supply (same behavior as an M81) if MAXTEMP is reached. This would cause heating to stop, even if a MOSFET fails and becomes stuck in the on position. Can this be added as a configuration option?

**Comment by KiteLab** [comment]
Since all the temperature errors use kill() now - that's already implemented but not configurable.

**Comment by 1-23** [comment]
Hmm, that's now how mine behaves. I'll pull the latest version, play with it a little, and report back. Thanks!

**Comment by thinkyhead** [comment]
@1-23 Currently `kill()` does this:
```cpp
pinMode(PS_ON_PIN, INPUT);
```
…but maybe on your machine it needs to do this:
```cpp
OUT_WRITE(PS_ON_PIN, PS_ON_ASLEEP);
```

**Comment by ntoff** [comment]
I use an xbox 360 PSU on one printer which requires the PSU's ps_on pin go high. Does that affect the way kill() works?

**Comment by 1-23** [comment]
Updating to the latest version fixed it. Sorry for the false alarm!
