### ISSUE TITLE
Compiler going nuts?

### ISSUE THREAD

**Issue by justmyopinion** [MarlinFirmware/MarlinDev#177]
I made a compilation of todays master with arduino 1.65.
I changed block_buffer_size from 16 to 64 bytes before compilation.
With 16 bytes dyn memory used was 41 % but with 64 bytes 86% was used and memory low warning. What is it here that is hard to understand?

**Comment by Wackerbarth** [comment]
"block_buffer_size from 16 to 64 bytes" -- No, you changed from 16 ENTRIES to 64 ENTRIES. Each entry is many bytes.

**Comment by justmyopinion** [comment]
Ok thankyou ..lacking knowledge of system needs may explain here :-).
I was investigating a bit for optimization.
