### ISSUE TITLE
Commands to enable/disable Filament Sensor

### ISSUE THREAD

**Issue by eboston** [MarlinFirmware/MarlinDev#185]
I have been looking at adding a filament sensor to my Printrbot Simple Metal.  I think I have everything worked out and will be back porting the current FILAMENT_RUNOUT_SENSOR logic to the older branch Printrbot uses.  However, I noticed that the check of the filament sensor only occurs if printing from the SD card.  What I was thinking of doing was to add two new code, M601 and M602, to enable/disable the filament sensor.  So if not printing from the SD card, you can put M601 in your startup code to enable the sensor and then a M602 in the end code.  These two commands could also be instead be name start/end printing so any other code you only want to run when printing could know  if a print job is running or not.

This would be a change to be added after the next version is released.  It might be a bit before I would be ready to add it into, if there is interest in it.  If not, I'll just use it in my own version for now.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3857
