### ISSUE TITLE
Code refinement only

### ISSUE THREAD

**Issue by justmyopinion** [MarlinFirmware/MarlinDev#195]
In temperature. cpp
watchdog_reset should be made conditional.

**Comment by thinkyhead** [comment]
You'll note that the original developers of Marlin chose not to make it conditional in `temperature.cpp` but instead to define it as an empty function in `watchdog.h` when `WATCHDOG` isn't enabled. I agree that making it conditional so that `watchdog.h` isn't even included is cleaner.
