### ISSUE TITLE
eeprom stuck

### ISSUE THREAD

**Issue by Sungod3000** [MarlinFirmware/MarlinDev#202]
Hi, I tested the dev version for its autolevel ability and that work as expected, there is just one thing that  behaves weird. 
When eeprom is enabled the m501 and m502 dont seem to show an effect. I have Z_PROBE_OFFSET_FROM_EXTRUDER set to a specific value but when I change it in firmware and want to reset it with 502 and 501 its stays on the old value until I disable eeprom. 

Not 100% sure if its an user error or bug but I ve never seen this so fyi.

**Comment by KiteLab** [comment]
With M502 you read the Configuration.h content into the RAM.
With M501 you read the EEPROM content into the RAM.
With M500 you write the RAM content into the EEPROM.

To change the EEPROM content to the Configuration.h content you need a: M502 M500.
The RAM content is what's actually used.
The EEPROM content is copied into the RAM on every boot.
