### ISSUE TITLE
what am I missing?

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/MarlinDev#207]
I just dnld 8ba58d5b22 and there is no INO file in it and it only has what is typically the MARLIN folder in a "MarlinDev-master" folder.

Is this an error or have the rules changed?

**Comment by clefranc** [comment]
@ruggb If you scroll down on the master branch you'll read this:

## Current Status: Reorganization of Source Files

##### Testing of the 1.1 Release Candidate is under way. Marlin development needs to proceed with caution while the structural changes being implemented here are completed.

There is a MAJOR change in Marlin core configuration files and libraries. Hopefully, it'll be resolve shortly, look for another announcement when everything will be in place.
