### ISSUE TITLE
Another cool project!

### ISSUE THREAD

**Issue by clefranc** [MarlinFirmware/MarlinDev#208]
https://www.kickstarter.com/projects/dobot/dobot-robotic-arm-for-everyone-arduino-and-open-so

![untitled](https://cloud.githubusercontent.com/assets/4294448/10013239/9a75b1aa-60dd-11e5-91ce-7fdf073ffbb4.png)

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3859
