### ISSUE TITLE
PlatformIO fail when settings use U8glib

### ISSUE THREAD

**Issue by Nandox7** [MarlinFirmware/MarlinDev#216]
Hey,

When trying to run platformio with settings that require the usage of the U8glib, for example the Full Graphics LCD controller, it fails to compile missing to find the U8glib.h file.

```
Marlin.ino:44:101: fatal error: U8glib.h: No such file or directory
compilation terminated.
scons: *** [.pioenvs/mega2560/src/tmp_ino_to.o] Error 1
```

I did tried to manually install the lib for platformio using: platformio lib install 9
(as seen here: https://libraries.io/platformio/U8glib)

It install correctly but still doesn't work.

**Comment by Wackerbarth** [comment]
The start of PlatformIO support was entered at the request of one of our users who had promised to "flesh it out". However, he never provided any updates. Unless someone fixes it, we will soon remove it entirely.

**Comment by Nandox7** [comment]
I can look into this then as I'd really like to avoid using the junky Arduino UI.

**Comment by clefranc** [comment]
@thawkins https://github.com/MarlinFirmware/Marlin/issues/2472

**Comment by thawkins** [comment]
Platformio lib install 7 

Works for me for a ramps card. 

Im not sure what extra is needed to "flesh it out", a number of folks over on printrbottalk are already using it to build marlin for printrboards. It works. Does it need any more. 

If its docs that are needed then i will try and write something  this week end.

**Comment by Nandox7** [comment]
Got it.
With lib install 7 it works.

Maybe just add that to the docs/readme. As more like me may just find first
the lib install 9 and it will fail.



-Nando

**Comment by thawkins** [comment]
I will start a wiki page on the release repo to document using platformio
with marlin.

**Comment by Nandox7** [comment]
Perfect! If i can help in any way please let me know.

PS: I've been searching but haven't found answer for thi yet. Is it
possible to just compile one environment?
I just need the atmega2560 but ifi  do platformio run it will compile all
the ones defined. Solution so far isto edit the ini file and remove the
entries for the ones i dont want.

**Comment by thawkins** [comment]
Platformio run -e mega2560

**Comment by thawkins** [comment]
http://docs.platformio.org/en/latest/userguide/cmd_run.html

**Comment by thinkyhead** [comment]
Sorry this issue is lingering for so long. As soon as 1.1.0 is released we will be migrating code into the new file layout (as in the MarlinKimbra fork), and we'll be paying much more attention to issues in MarlinDev to see what still applies with the latest code.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3860
