### ISSUE TITLE
Safety Kill Problems with Pseudo Thermistor

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/MarlinDev#221]
I'm trying to test part of the current firmware on the electronics without any actual heaters.
```
// Use a simulated temperature probe
#define TEMP_SENSOR_0 998
```
But I'm getting killed by the MIN_TEMP on HEATER_0 safety check.

Has anyone gotten this to work of the pseudo sensors since the MIN_TEMP kill was added?

**Comment by AnHardt** [comment]
Yes.

Retested in RC. 999, 998, MIN- and MAX- errors, normal operation, with and without uncommented temperature settings, for bed and the first nozzle. All is working perfect.

**Comment by Wackerbarth** [comment]
OK, I found something that I failed to set properly.
