### ISSUE TITLE
Marlin Main_cpp missing bracket

### ISSUE THREAD

**Issue by sebastian-dev** [MarlinFirmware/MarlinDev#248]
in Marlin_main.cpp there is an missing bracket near line 7158

when you use the option: FAST_PWM_FAN

          TCCR5B |= val;
          break;
      #endif
  }
  } <----- this is missing

#endif // FAST_PWM_FAN

**Comment by AnHardt** [comment]
Solved by merging https://github.com/MarlinFirmware/MarlinDev/pull/251
