### ISSUE TITLE
Dual X/Y/Z

### ISSUE THREAD

**Issue by caenan0** [MarlinFirmware/MarlinDev#255]
Not so much an issue but rather a comment in case anybody has been wanting to build a similar setup - my design has dual Y/Z and dual X carriage all enabled within Marlin and despite the sanity checks usually preventing this from happening, it compiles and runs prints without issue (so far) if you just comment out those errors.

**Comment by Wackerbarth** [comment]
How do you have things set up? By that, I mean, which pins control the various stepper motors?

**Comment by caenan0** [comment]
Using an Azteeg X3 Pro with 8 stepper outputs, so basically 2 for each axis XYZE.

**Comment by AnHardt** [comment]
Interesting concept with that 4? 6? 8? carriages.
Or do you mean "dual Y/Z and dual X __stepper__" ?

**Comment by caenan0** [comment]
@AnHardt, the latter.

**Comment by Roxy-3DPrintBoard** [comment]
Is this just to increase the force moving the carriage around?   Is this to get higher travel speed?

**Comment by caenan0** [comment]
For the Y/Z, I needed the extra power of an extra motor to drive large components (my design has just under 5 cubic feet of build volume). If you're not familiar with the dual X arrangement, you can check out http://www.thingiverse.com/thing:115885.

**Comment by Roxy-3DPrintBoard** [comment]
That is cool!  With some Slicer changes you could optimize a lot of things.

**Comment by caenan0** [comment]
So if anybody wants to actually see this in action, I've got a kickstarter video up here: https://www.kickstarter.com/projects/aon3d/aon-real-industrial-3d-printing
