### ISSUE TITLE
strange auto level behaviour...

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/MarlinDev#27]
Org Link: https://github.com/MarlinFirmware/Marlin/issues/1769

**Comment by Sniffle** [comment]
This still needs to be looked into, I didn't pay that close of attention to the process as it ran through the auto leveling sequence but i remember it skipping a few steps previously.  I'll report back on this soon.

**Comment by thinkyhead** [comment]
After #62 and #63 are merged give it another test. We're waiting for more feedback and some edits before they will be ready to go.
