### ISSUE TITLE
Using printer like boards wackerbarth's install

### ISSUE THREAD

**Issue by iplayfast** [MarlinFirmware/MarlinDev#290]
Setting up arduino Preferences, additional boards managers urls with 
https://raw.githubusercontent.com/Wackerbarth/MarlinDev/platform/package_marlinfirmware_index.json
will allow boards to be installed.
However it gets a crc error so install fails.

**Comment by iplayfast** [comment]
Just found proper json file at 
    https://raw.githubusercontent.com/MarlinFirmware/MarlinDev/platform/package_marlinfirmware_index.json

Same result. CRC doesn't match file is corrupted.

**Comment by Wackerbarth** [comment]
I just downloaded it without any problem.

Make sure that your .json file specifies version 1.0.2

I just flushed everything from my Arduino15 support folder (where the IDE stores all of its preferences and downloaded pieces) and reinstalled using the board manager without any problem.

**Comment by iplayfast** [comment]
Yup deleting .arduino15 and starting fresh fixed it. Sorry bout that.

**Comment by Wackerbarth** [comment]
I think think that I see a problem in the IDE. When there is a checksum error, the file needs to be flushed and reloaded.

**Comment by iplayfast** [comment]
On 15-11-25 07:36 AM, Richard Wackerbarth wrote:
>
> I think think that I see a problem in the IDE. When there is a 
> checksum error, the file needs to be flushed and reloaded.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MarlinFirmware/MarlinDev/issues/290#issuecomment-159595291>.
>
I think you've got it.
