### ISSUE TITLE
Z_PROBE_OFFSET_FROM_EXTRUDER not working

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/MarlinDev#30]
Org link: https://github.com/MarlinFirmware/Marlin/issues/1894

**Comment by Sniffle** [comment]
It is currently working properly for cartesian printers, specifically the prusa i3 Variants, testing still needs to be done on other variants.

**Comment by thinkyhead** [comment]
This topic is no longer topical, and the offset definitely works in the latest code.
