### ISSUE TITLE
LCD menu (REPRAP_DISCOUNT_SMART_CONTROLLER) is extremly slow

### ISSUE THREAD

**Issue by ihouses** [MarlinFirmware/MarlinDev#306]
Hello,

Most of the times that I use the LCD menu the answer to the rotatory encoder is very bad, is it because the polling speed is too low? If I use the LCD while I am printing from the SD card is even worst.

I have a delta and I have plenty of problems. Can anyone point me out a discussion list or so related with deltas?

**Comment by thinkyhead** [comment]
Sorry this has gone unanswered for so long. Most of our effort has been on the 1.1.0 release, so some topics here have been neglected. Have you been able to get better performance by tuning parameters? If your electronics are on the slower side (Mega2560 or lesser) then you should try reducing `DELTA_SEGMENTS_PER_SECOND` to get better LCD performance.
