### ISSUE TITLE
Feedrate Very Slow between Z Probs for Auto Bed Levelling

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/MarlinDev#31]
Org link: https://github.com/MarlinFirmware/Marlin/issues/2328

**Comment by thinkyhead** [comment]
@CarpetHead I'm going to look into getting this debugged asap. Can you confirm that the problem still exists in the latest code-base at https://github.com/MarlinFirmware/MarlinDev ? You've stated that removing both `M140` and `M104` fixed the issue for you. Does that mean that removing either one fixed it? Or did you need to remove both?

For our reference, here are the command meanings:

    [M104](http://www.marlinfirmware.org/index.php/M104): Set hot end temperature (no wait). T=hotend, S=temp
    [M109](http://www.marlinfirmware.org/index.php/M109): Wait for extruder(s) to reach target temp. T=target, R/S=temp
    [M140](http://www.marlinfirmware.org/index.php/M140): Set bed temperature (no wait). S=temp
    [M190](http://www.marlinfirmware.org/index.php/M190): Wait for bed temp to reach target temp. R/S=temp

The commands that are causing you trouble are those that set the temperature but don't wait for the temperature to be reached before proceeding with the next command in the queue. They don't do anything very unusual. They just set the target temperature, and the temperature code then proceeds to apply power to the heaters while the machine is free to do other things. So, I think these commands are only involved in some ancillary way with the feedrate problem.

Probably the best approach is to just make sure to reset the feedrate to the max speed after each probe. But, it would be good to see (by logging) what the feedrate is set to at every stage along the way.
