### ISSUE TITLE
There is a double percent mark on my screen. How do I remove the extra percent mark?

### ISSUE THREAD

**Issue by a4jp-com** [MarlinFirmware/MarlinDev#311]
![img_0177](https://cloud.githubusercontent.com/assets/9621044/11916707/064e51aa-a726-11e5-97b7-82067154be1e.JPG)

This is not a big thing but how do I remove the extra percentage mark?

**Comment by Roxy-3DPrintBoard** [comment]
Quick question:   What happens if you adjust the feed rate to 100.1% and 99.9%   ?   I'm wondering if that extra % is left over from a previous refresh cycle of the display?

**Comment by a4jp-com** [comment]
I'm trying to fix the button code here (https://github.com/MarlinFirmware/MarlinDev/issues/310#issuecomment-166125362) and can't compile because of an error, but as soon as I get that figured out I can try to set the feed rate. Sorry about that.

**Comment by KiteLab** [comment]
```
  #if LCD_HEIGHT > 2

    #if LCD_WIDTH < 20

      #if ENABLED(SDSUPPORT)
-        lcd.setCursor(0, 2);
+        lcd.setCursor(0, 1);
        lcd_printPGM(PSTR("SD"));
        if (IS_SD_PRINTING)
          lcd.print(itostr3(card.percentDone()));
        else
          lcd_printPGM(PSTR("---"));
          lcd.print('%');
      #endif // SDSUPPORT

    #else // LCD_WIDTH >= 20

      lcd.setCursor(0, 1);
```

**Comment by a4jp-com** [comment]
@KiteLab that tiny change of the number 2 to 1 fixed 2 bugs ^^ Thank you so much. I can now see the SD card line.

![img_0211](https://cloud.githubusercontent.com/assets/9621044/11918646/e9a10212-a77c-11e5-951e-f6196f720ca1.JPG)

@Roxy-3DPrintBoard would you like me to test the feed rate or is this looking okay now?

**Comment by Roxy-3DPrintBoard** [comment]
No!   I was just guessing at possible causes.  KiteLab nailed this one!

**Comment by a4jp-com** [comment]
Okay. Nice. 

If you could add this to the updated dev files it would be great.

Thank you so much @KiteLab .
