### ISSUE TITLE
How can I reduce the power/noise of the y-stepper with the digital trimpot (pin file/stepper file?)

### ISSUE THREAD

**Issue by a4jp-com** [MarlinFirmware/MarlinDev#329]
I can see the m codes below online and pages explaining that reducing the power from the trimpots can get rid of noise from a stepper.

M907 - Set digital trimpot motor current using axis codes.
M908 - Control digital trimpot directly.

I don't want to destroy the stepper I have and this is my first time trying to adjust a value like this to fix a noisy y stepper so any help is greatly appreciated.

When I tried M907 Y or M908 Y in Pronterface nothing happened.

-----------------------------

These are the current pins for the digipots

#define DIGIPOTSS_PIN 38
#define DIGIPOT_CHANNELS {4,5,3,0,1} // X Y Z E0 E1 digipot channels to stepper driver mapping

How do I check the current values?

--------------------------------

http://reprap.org/wiki/Rambo_firmware

Marlin

You can adjust the motor driver settings in Configuration_adv.h: #define MICROSTEP_MODES and #define DIGIPOT_MOTOR_CURRENT

----------------------------

https://forum.lulzbot.com/viewtopic.php?t=702

http://3dprintboard.com/showthread.php?12323-I-need-your-help-Y-motor-making-a-loud-noise

https://www.reddit.com/r/Reprap/comments/37tofz/all_firmware_settings_for_x_and_y_axis_are_the/

----------------------------

**Comment by nothinman** [comment]
So... you'd normally reduce noise by reducing current flowing through the windings of the stepper, but this you probably already know.
You won't destroy it. Both Allegro drivers and DRV drivers have thermal shutdown. Steppers would likely get hot, but that's it. It will take some time, so you can verify this with your hand :)
Current (and the digipot value) would depend on both voltage and windings' resistance, so a bit hard to answer your question without a crystal ball ;-)
