### ISSUE TITLE
G-code 1 might be broken

### ISSUE THREAD

**Issue by a4jp-com** [MarlinFirmware/MarlinDev#330]
When I send the command G1 Z14, this should keep moving the bed down 14mm, shouldn't it? It goes down and just stays at 14mm. Is this normal? How do I get the bed to keep going down 14mm when I send G-code? G0 seems the same.

**Comment by Nandox7** [comment]
You need to change from absolute to relative move.
Check GCodes G91 and G92.

**Comment by a4jp-com** [comment]
I typed in G91 Z5 but nothing happened. It's also the same for G92.

**Comment by a4jp-com** [comment]
Do I have to use a combination of the G-codes?

**Comment by Nandox7** [comment]
Nop. You use G91/92 independently.
Example:
---
G91
G1 Z10
---
or
---
G92
G1 Z10
---

**Comment by a4jp-com** [comment]
I see. Thank you so much for that @Nandox7 . 

I had a bad sample of code and now I know how to get everything working ^^

G91 ; Change movement system to relative position system - calculates from current position
G1 Z25 ; Z25 Moves platform down 25mm
