### ISSUE TITLE
stepper driver info?

### ISSUE THREAD

**Issue by coalman321** [MarlinFirmware/MarlinDev#340]
i need some info on how the firmware handles the driver step, dir and enable pins while in 2 states.
the first is while the motor is being moved and second while that motor is not moving but others are.
any help would be great!
Thanks

**Comment by Roxy-3DPrintBoard** [comment]
Can we send you an invoice for our time to answer your questions while we improve this software you get for free???

**Comment by KiteLab** [comment]
The ISR in stepper.cpp is actually setting the pins.
What to do is calculated in planner.cpp.

**Comment by coalman321** [comment]
I apologize but I am not attempting to copy anything if that's what you think. I am attempting to drive a laser from the 3 pins that control extruder 2 on my board. I'm trying to learn why when I hook the direction pin to it, it turns on even when it is not mentioned in the move.

**Comment by KiteLab** [comment]
Search the issues here and/or in MarlinFirmware/Marlin.
We already have had this question - and got a satisfying answer.

**Comment by KiteLab** [comment]
https://github.com/MarlinFirmware/Marlin/issues/2809

**Comment by coalman321** [comment]
Thanks
