### ISSUE TITLE
FYI - Babystepping on CoreXY machine

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/MarlinDev#341]
Babystepping for Z works on my CoreXY machine. Apparently, contrary to information I rcvd here it has always worked for CoreXY machines at least in some versions of 1.0.x. I never tried it as I didn't know how to make it work. I finally implemented it in RC3, then found out from someone else using 1.0.x that it works for them also. - It requires commenting out the define for BABYSTEPPING_XY when BABYSTEPPING is uncommented. BABYSTEPPING_XY is what does not work for CoreXY.

**Comment by KiteLab** [comment]
https://github.com/MarlinFirmware/Marlin/issues/2935#issuecomment-175541629
