### ISSUE TITLE
SD Fat library should be updated

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/MarlinDev#344]
The SD Fat library that we include is not the current release from that library's author.
This causes compilation errors with some of the more recent compiler releases.

https://github.com/greiman/SdFat.git

**Comment by thinkyhead** [comment]
SdFat has diverged a lot. In fact, for the features we use, such as long filenames, we would have to use https://github.com/greiman/SdFat-beta. I have already tried to do the upgrade once, but found it a bit daunting and went back to trusting our little slice of SdFat.
