### ISSUE TITLE
Question about Team Members

### ISSUE THREAD

**Issue by Roxy-3DPrintBoard** [MarlinFirmware/MarlinDev#348]
Did GitHub change the way they do posts and issues?   Every Collaborator now shows up as a 'MarlinFirmware Member' even though I didn't change anything?

Can somebody tell me who and what changed?

**Comment by thinkyhead** [comment]
Github changed the wording, apparently. They keep changing things.

**Comment by a4jp-com** [comment]
I think the system got a few tweaks but as long as people are volunteering and helping out in their free time to make the software better I don't think it's a problem.
