### ISSUE TITLE
Can't upload using latest Arduino 1.6.7 IDE

### ISSUE THREAD

**Issue by Nprod** [MarlinFirmware/MarlinDev#378]
OK, so i'm trying to use the 1.6.7 Boards Manager package by @Wackerbarth with a Melzi board (Sanguino 1284p@16mhz) and it's throwing an error:

> #error This file is obsolete and needs to be revised

I tried commenting out that line in pins_arduino.h and it moves forward only to give me timeout errors like this:

> avrdude: stk500v2_ReceiveMessage(): timeout

I've tested this with two identical Melzi boards and two different PC's but the errors follow the same pattern. I can upload fine to other AVR boards like an Arduino Nano through the standard board configs provided by the IDE so my guess is this is a problem with the Marlin-Sanguino configuration package.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3852
