### ISSUE TITLE
Hangout -- Saturday August 15 UTC 2000 

### ISSUE THREAD

**Issue by Wackerbarth** [MarlinFirmware/MarlinDev#38]
Name  | Summer Time Zone
------------ | -------------
@thinkyhead    |  UTC-7
@Wackerbarth  |   UTC-5
@Jnesselr    |    UTC-5
@clefranc     |   UTC-4
@alexborro    |   UTC-3
@fmalpartida   |  UTC+1
@AnHardt     |    UTC+1
@Wurstnase    |   UTC+1
@CONSULitAS   |   UTC+1
@paclema     |    UTC+1
@boelle    |      UTC+1
@emartinez167   |  UTC+8
@ntoff    |       UTC+10

[The "Official" UTC Clock](http://www.timeanddate.com/time/aboututc.html)
[Link to the Hangout](https://plus.google.com/hangouts/_/gxn3wrea5gdhoo223yimsiforia)

Please provide input about what we need to discuss.
[Link to Google Document listing discussion topics (Week 33)](https://docs.google.com/document/d/1GmKjDVOKLj6f6s76ZL99LvCPOwy_PkYK57M88Q2oNdM/edit?usp=sharing)

**Comment by fmalpartida** [comment]
Ejem is The net one?
