### ISSUE TITLE
Is EXT_SOLENOID obsolete?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/MarlinDev#381]
I see that the `M380` and `M381` commands that depend on `EXT_SOLENOID` and the `SOLn_PIN` pins are not being activated by any of Marlin's current configurations. None of the pins files define these pins. Is there any configuration that demonstrates or uses this feature? Is this feature still required for extruder-mounted solenoids?

**Comment by Blue-Marlin** [comment]
Interesting features we have. Could be used for a dribble stop, extruder on LED, multi material paste extruders, ...
Seems to need some more documentation - not necessarily an example in one of the configs..
