### ISSUE TITLE
Dual extruder Filament_Runout_Sensor

### ISSUE THREAD

**Issue by sailorpete12** [MarlinFirmware/MarlinDev#385]
Hi Everyone!

This is my first post on here and I'm not too familiar with how Github works. be nice :) ( C&P from the Marlin repository, seems this might be a better place for it.

My issue - I have been working on a IR gate filament sensor which is Incorporated into the extruder housing (see link for my extruder http://www.thingiverse.com/thing:1064390) I have not updated the thing with the electronics yet. But

-How would this work with a dual extruder printer?
-Is the sensor I/O only corresponds to the active tool or is dedicated to only T0? for instance both the filament hardware sensor share the same I/O and one runs out, this will trigger the active tool to initiate the M600 Command. Or is this only for Tool_0. I have not completed the HW build for this to test it.

Secondly, I am using Octroprint which works very well, but going through the code the Filament_runout_sensor is only activated when printing via an SD card. how would this be tweaked to activated when printing via the serial port? would a 'M' Command need to be incorporated to set marlin to monitor the sensor which processing the serial commands but also disable when not printing. say this can be defined in the starting and ending Gcode?

Thanks for any help.

**Comment by Blue-Marlin** [comment]
Currently only one pin is tested. When connecting more than one switch you need a or/and in hardware. For simple switches this is trivial. For switches driving actively high and low you may need some more logic. EXT_SOLENOID could be helpful than.
Up to now there is only one extruder moved at a time. So the signal is always for the currently active extruder. With colour mixing we need a different concept then.
When we have a 'filament is out' signal M600 is called. This has no parameter for the extruder, but is always working with the current extruder. Up to now this should work. For colour mixing we have to extend that.
Up to now the long 'manual' pause in M600 confuses some hosts. They may think Marlin vanished. I think for that reason this feature is limited to sd-printing. When #3109 is in, you may experiment with dropping that condition.
