### ISSUE TITLE
Replace rotary encoder with push buttons

### ISSUE THREAD

**Issue by alessiobigini** [MarlinFirmware/MarlinDev#394]
Hi, i’ve made a keypad for my 3D printer, i use marlin firmware my question is, can i replace encoder with push buttons ?
Where i must do changes for remove rotary encoder?
Thanks so much!

**Comment by Blue-Marlin** [comment]
You can find some hints in https://github.com/MarlinFirmware/MarlinDev/issues/310

**Comment by alessiobigini** [comment]
@Blue-Marlin 
Thanks but I've already read #310 thread but i didn't got any solution
