### ISSUE TITLE
Can one manually enter bed levelling matrix for delta?

### ISSUE THREAD

**Issue by zlikovski** [MarlinFirmware/MarlinDev#399]
I didn't succeed to find the answer on the net, so before I do something stupid and crash my printer, I'd like to consult with wiser wo/men,
I have a delta printer (home made), based on the kossel design. I can level it nicely with repetier firmware. Now, my question is wether is it possible to take the levelling matrix from that levelling procedure and insert it in my marlin firmware?
There is a matrix in the planer.cpp. Maybe in some other place?

**Comment by Roxy-3DPrintBoard** [comment]
You can not do that currently.   But it is being worked on.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3850
