### ISSUE TITLE
"You’ve been removed from the Collaborators team on the MarlinFirmware organization."

### ISSUE THREAD

**Issue by nothinman** [MarlinFirmware/MarlinDev#401]
Explain yourselves.

**Comment by fmalpartida** [comment]
I got one too.

**Comment by Roxy-3DPrintBoard** [comment]
> Explain yourselves.
@nothinman  Not even a 'Please' in front of that???   

Did you see you both have Write access to all three repositories?

**Comment by nothinman** [comment]
@Roxy-3DPrintBoard I've noticed after opening this ticket. Well, that was only partially serious, but I guess people don't try to read the sentences the way they were meant to be read, if they're lacking emoticons :-)
'Please' is when you do something wrong and ask for forgiveness, or ask for something you didn't already have :-)

**Comment by Roxy-3DPrintBoard** [comment]
A while ago GitHub changed the meaning and usage of 'Collaborator'.   Today I started to clean up some of the Team usage of MarlinFirmware.   More still needs to be done.
