### ISSUE TITLE
Ability to follow cubic Bézier splines

### ISSUE THREAD

**Issue by giomasce** [MarlinFirmware/MarlinDev#417]
[this issue was already filed as MarlinFirmware/Marlin#3022, but it was closed and I was suggested to re-open it here]

I added support for drawing Bézier cubic splines to Mariln. The code is here: https://github.com/giomasce/Marlin/commits/Development. I use it for my Marlin-based laser cutter and it apparently works with no problems. A few comments about the implementation are both in the code and in MarlinFirmware/Marlin#3022.

Please note that the patches are based against a rather old version of Marlin. I do not have a recent enough building environment, so I cannot rebase them on the development branch. However the code is rather independent from the original codebase, so it should not be difficult to port it.

**Comment by thinkyhead** [comment]
I'm finally getting a chance to examine the code. I will comment more when I have read it thoroughly!

**Comment by thinkyhead** [comment]
Ok, looks like it should be easy to integrate with the latest code. I will package it up and post it for consideration.

**Comment by thinkyhead** [comment]
@giomasce See MarlinFirmware/Marlin#3744 for the updated implementation.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3843
