### ISSUE TITLE
moving issues?

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/MarlinDev#419]
@thinkyhead Scott, is it possible to move issues across repro's?

**Comment by jbrazio** [comment]
no

**Comment by jbrazio** [comment]
(only manually or API)

**Comment by boelle** [comment]
so with API it becomes a yes anyway

**Comment by CONSULitAS** [comment]
@boelle @thinkyhead 
Perhaps Google is our friend here:
https://www.google.de/search?q=github+move+issues+between+repositories&ie=UTF-8&oe=UTF-8&hl=de-de

https://github.com/google/github-issue-mover

**Comment by boelle** [comment]
yep, i used that one before on some other gihub work...

as long you have write access at both ends it works

**Comment by thinkyhead** [comment]
The auto-mover doesn't get everything. For the moment I vote we just keep both repos open until we get this release out. Some good discussions are still open around here (for better or worse).

**Comment by Roxy-3DPrintBoard** [comment]
> For the moment I vote we just keep both repos open until we get this release out. Some good discussions are still open around here (for better or worse).

When we know we won't lose anything...   (When the time is right)   My vote is it can go away...

If we are going to start a new thread for this:  https://github.com/MarlinFirmware/MarlinDev/issues/398

I guess it should be done on the Marlin side of the fence.

**Comment by Roxy-3DPrintBoard** [comment]
> For the moment I vote we just keep both repos open until we get this release out. Some good discussions are still open around here (for better or worse).

When we know we won't lose anything...   (When the time is right)   My vote is it can go away...

If we are going to start a new thread for this:  https://github.com/MarlinFirmware/MarlinDev/issues/398

I guess it should be done on the Marlin side of the fence.

**Comment by Roxy-3DPrintBoard** [comment]
> For the moment I vote we just keep both repos open until we get this release out. Some good discussions are still open around here (for better or worse).

When we know we won't lose anything...   (When the time is right)   My vote is it can go away...

If we are going to start a new thread for this:  https://github.com/MarlinFirmware/MarlinDev/issues/398

I guess it should be done on the Marlin side of the fence.

**Comment by Roxy-3DPrintBoard** [comment]
> For the moment I vote we just keep both repos open until we get this release out. Some good discussions are still open around here (for better or worse).

When we know we won't lose anything...   (When the time is right)   My vote is it can go away...

If we are going to start a new thread for this:  https://github.com/MarlinFirmware/MarlinDev/issues/398

I guess it should be done on the Marlin side of the fence.

**Comment by jbrazio** [comment]
I backup @thinkyhead.

**Comment by boelle** [comment]
This issue was moved to MarlinFirmware/Marlin#3841
