### ISSUE TITLE
Z_SAFE_HOMING - Z_RAISE_BEFORE_HOMING

### ISSUE THREAD

**Issue by AnHardt** [MarlinFirmware/MarlinDev#53]
__What is `Z_RAISE_BEFORE_HOMING` doing now?__
- If `!Z_SAFE_HOMING` we raise Z by this amount before any other move, when ABL is defined (else `Z_RAISE_BEFORE_HOMING` is not defined).
- If `Z_SAFE_HOMING` homes X and Y. Then drives to `[Z_SAFE_HOMING_X_POINT, Z_SAFE_HOMING_Y_POINT, Z_RAISE_BEFORE_HOMING]` when `Z_HOME_DIR > 0` (not a z-max-endstop). 

__What is `Z_RAISE_BEFORE_HOMING` for?__
- I'd like to see it as a raise of the nozzle to jump over obstacles on the bed (clamps, screws). In this case it should be independent from ABL and go into the homing section.
- Together with `Z_SAFE_HOMING` it's used in the wrong order. Z should be lifted first, then homing X and Y, then moving to the mid and finally probing Z.
- Together with `Z_SAFE_HOMING` (which makes the most sense with a z-probe - not endstop) it's used instead of a `RETRACT_BEFORE_SERVO_ACTION [Z]` (aka `Z_RAISE_BEFORE_PROBING`). As I don't expect obstructions in the middle of the bed, a lift to max (`Z_RAISE_BEFORE_HOMING`, `RETRACT_BEFORE_SERVO_ACTION [Z]`) should be sufficient. (remember, we do not know our z-height until now. Moving upwards is dangerous!)

__What is `Z_SAFE_HOMING` doing now?__
- See above.

__What is `Z_SAFE_HOMING` for?__
- If we have a z-max-endstop or a z-min-endstop we can home everywhere.
- If we have a z-probe (and neither a z-max-endstop nor a z-min-endstop), we can't home Z at every XY.  The probe needs to be within the bed. For the middle of the bed it's very unlikely the probe will not hit the bed - therefore this is our default; but we could probe anywhere in the area what is described by ( `LEFT_PROBE_BED_POSITION`, `RIGHT_PROBE_BED_POSITION`, `FRONT_PROBE_BED_POSITION`, `BACK_PROBE_BED_POSITION`).

__What is needed for `Z_SAFE_HOMING`?__
X and Y must be homed before Z. The probe has to hit the bed. If we have a probe, we have to deploy and stow it.

__Has this got anything to do with ABL?__
No. It has to do with the ability to probe, where in the simplest case the endstops are the probe. In the second simplest case we have a fixed (inductive, captive, FSR, ...) probe, we no not have to deploy. In the most complicated case we have to deploy the probe (servo, sled, allenkey, ...)
Yes, because the ability for probing was invented for ABL. So ABL depends on probing, but not the other direction.

__What to do?__
- Move the definitions for `Z_SAFE_HOMING` and `Z_RAISE_BEFORE_HOMING` to the homing section.
- Recognize `Z_RAISE_BEFORE_HOMING` even when ABL is not enabled.
- Change the move to the middle for `Z_SAFE_HOMING` to not do a lift. But make a separate lift to deploy the probe as-needed for that type of probe. (additional lift = `(Z_RAISE_BEFORE_PROBING - Z_RAISE_BEFORE_HOMING > 0) ?  Z_RAISE_BEFORE_PROBING - Z_RAISE_BEFORE_HOMING : 0`)
- Cleanly deploy and stow the z-probe when needed.

**Comment by thinkyhead** [comment]
Let's systematically fix this stuff. I'm off to bed now, need to go and get a tetanus shot in the morning…. So some time over this weekend we should make these all make sense.

**Comment by AnHardt** [comment]
Thinking a bit further there is only one lift you need. You need that much lift you can operate all possible maneuvers safely. This lift will differ, depending on your type of probe, but for every combination of circumstances there is ___one save minimal lift to make all operations___. I can't find any combination of circumstances where the minimal needed lift could be zero or less.
The remaining special z-heights are:
Zero - nozzle tip touches the bed.
Z_PROBE_OFFSET_FROM_EXTRUDER - difference from Zero to the trigger point of the probe.
A save action height - to operate G28 and G29 without crash (with your kind of probe).

For servo probes i made a little scad-movie (https://www.youtube.com/watch?v=w9RO8eRG2fU).

**Comment by Wackerbarth** [comment]
I see a need for two lift numbers.  One for deploy/retract and the other to control the probing motion.
To deploy/stow, we want our minimum height (In extruder coordinates) to be Z_PROBE_OFFSET_FROM_EXTRUDER + Z_PROBE_DEPLOYMENT_CLEARANCE. This is the same as  Z_PROBE_DEPLOYMENT_CLEARANCE in probe coordinates.
When we actually probe, we want to raise to Z_PROBING_HEIGHT in probe coordinates (aka Z_PROBE_OFFSET_FROM_EXTRUDER + Z_PROBING_HEIGHT in extruder coordinates.)

**Comment by AnHardt** [comment]
Is there any good reason for not just taking the bigger one? Yes, in one of the cases you can save a few mm of movement - is that worth the trouble.
We could save a lot of code if we'd do all probe activating/deactivating like the Z_PROBE_END_SCRIPT. Of cause we then need a Z_PROBE_START_SCRIPT to. A 3 part sequence (start - mid - end) with a mid repeatable if the probe is still triggerd/untrigerd, would also do the job for allen-key-probes. The aim i see here is to a) unify the probe handling for less complexity and code, b) save some space in the PROGMEM, c) therefore move the complexity to the CPP maybe with a separate `Configuration_Probe.h`.
The complexity for every single type of probe is low, mostly only driving to some coordinates, switching a magnet or servo, testing if the probe is still triggered or not. Everyone could easily make it's  own sequence for activating/deactivating his/her special probe.

**Comment by Wackerbarth** [comment]
I fully agree with the idea of treating ALL probes the same with customized micro-coded deploy, probe, and stow sequencing scripts. As for distinguishing between the difference in "PROBING_HEIGHT" and "ADDITIONAL_DEPLOYMENT_CLEARANCE", I have no idea how much they differ.

Particularly if we start splitting up the Configuration into multiple sections, we can easily have comments documenting how to choose the appropriate value in that file. However, we first have to convince Scott to abandon his "everybody has everything in one file" configuration. (IMHO, the sooner the better)

**Comment by thinkyhead** [comment]
> we first have to convince Scott to abandon his "everybody has everything in one file" configuration

All I'm concerned with is avoiding disruption in migration from older Marlin for the time being. I have suggested in the past to break up the configuration into several parts by theme, but this has not been a popular idea. I say, go ahead and implement it, then see how much it is loved or hated. Try making the overridable configuration concept at the same time (where only altered options need to be included) and see how that goes over. Yes, my personal preference is still to keep the two self-documenting configuration files — not to split them up by theme, and not to add a `Configuration_overrides.h` (for example) file. My mind will be changed by seeing an actual implementation that people like, but someone with more enthusiasm than I will have to build it.

**Comment by Wackerbarth** [comment]
I can equally say that expecting every configuration to include EVERY option is also "not popular".

In fact, you have already "broken" that concept by treating DELTA and SCARA differently.

Utilizing a single unified configuration file (for those who wish to do so) is not incompatible with a structured scheme. Just think of it as a special "custom" case where EVERYTHING is overridden.

The problem is that your insistence that doing it that be "the rule" rather than "an exception" is forcing a burden on the rest of us.

**Comment by thinkyhead** [comment]
> you have already "broken" that concept by treating DELTA and SCARA differently

I just kept it as it was, but I would have preferred to keep those sections in all the other configurations too.

**Comment by thinkyhead** [comment]
> your insistence that doing it that way

You keep attributing feelings and intentions to me that have nothing to do with me. I have merely kept things as they have been historically to avoid breaking everyone's existing configurations, and only made gradual changes, adding warnings to `SanityCheck.h` for things that have changed. I have not presumed to rewrite the entire configuration scheme, a process which comes with many pitfalls.

**Comment by Wackerbarth** [comment]
Yes, I DO attribute intentions to you because you insist that, "for historical reasons", making any change to the scheme which PERMITS a structured scheme is OFF LIMITS and cannot be considered.

What is being proposed will not change anyone's configuration, nor REQUIRE that they change to a revised scheme. 
Anyone who has made ANY modifications to their personal configuration is, de facto, NOT using the "default" anyway. They can still compare theirs to your default and go from there.
The only thing that I really want to change that might affect them is that they would need to look in a slightly different place to find this "default" (de jour) configuration with all of the options expressly presented.

**Comment by thinkyhead** [comment]
> you insist that, "for historical reasons", making any change to the scheme which PERMITS a structured scheme is OFF LIMITS and cannot be considered.

I don't recognize myself in this mirror.

My feeling is that for "historical reasons" it's not a good idea to replace the configuration scheme for this release. But of course I am open to an experimental branch where this can be worked out. And once it's mature deploy it. But the work needs to be done first, and since you are so adamant, I think you should build it.

**Comment by Wackerbarth** [comment]
Look again, "it's not a good idea to replace the configuration scheme for this release"  I have already presented the concept, I have even attempted to update my presentation a few times to chase after all the changes that you continue to make to the configuration files. But you were unwilling to accept the concept then and I see no point in attempting to keep it "current" until you are ready to consider and discuss it.

**Comment by thinkyhead** [comment]
@Wackerbarth Hold on to your concept until such time as is more convenient. Meanwhile, please link in this thread to the branch in your fork where your new configuration scheme is implemented. As time allows someone will try to bring it up to date.

**Comment by Wackerbarth** [comment]
@thinkyhead -- Equally, also hold onto all of the suggestions of everyone else, and yourself, so that we can get RC1 out the door and thus make it "more convenient" for this and other changes to the file layout.  

We are wasting far too much time attempting to work around a scheme that is antiquated and that we have outgrown instead of reorganizing things to make it easier to accomplish the functional changes.
