### ISSUE TITLE
motors disabled

### ISSUE THREAD

**Issue by ruggb** [MarlinFirmware/MarlinDev#89]
I think this is an old issue but i couldn't find the thread.
Anyway, I thought I didn't like the idea of the motors disabling immediately after a move BUT.
my printer so far has held the position (I haven't printed anything heavy enough and xy movement is very neutral) and I find it very useful to manually micro adjust the Z0 after the print starts.
I am hoping u find a cure for babystepping on a corexy - at least for the Z axis as that is what my prime use would be. Then u can bring back the 60 second delay after commands r finished.

I am using dev 8/0/15 and the quickhome appears to be working flawlessly.
thx

**Comment by thinkyhead** [comment]
Will definitely look into polishing these areas and making everything work in a sane manner....

**Comment by AnHardt** [comment]
https://github.com/MarlinFirmware/Marlin/issues/2661
