### ISSUE TITLE
Firmware Retract?

### ISSUE THREAD

**Issue by CCS86** [MarlinFirmware/MarlinDev#90]
Hi guys,

I recently enabled firmware retraction on my machine (not running this dev branch of Marlin).

It works in the sense that G10/G11 triggers retractions and recoveries, and the FW retraction settings appeared in my EEPROM menu . But despite having a much slower "recovery" feed rate set, both motions appear to be the same speed (fast).

Any thoughts as to why this might happen?

Thanks!

**Comment by thinkyhead** [comment]
Could be a bug. I'll look into this over the next couple of days. Probably some simple oversight.

**Comment by CCS86** [comment]
Thanks @thinkyhead !

**Comment by CCS86** [comment]
@thinkyhead , Did you happen to find the disconnect?

**Comment by Roxy-3DPrintBoard** [comment]
ThinkyHead may be slow to answer...  I think he is moving.

**Comment by thinkyhead** [comment]
> may be slow to answer

That's possible…

@CCS86 The code for `G10` / `G11` does appear now to set `feedrate` explicitly to the retract or recover rate. Are you still seeing this any more, or have you switched back to slicer retraction?

**Comment by CCS86** [comment]
I have been using slicer based retraction for now. I'm looking forward to
trying the new Marlin release, but might have to wait until someone makes
an Ultimaker branch of it.

**Comment by thinkyhead** [comment]
> might have to wait until someone makes an Ultimaker branch

@CCS86 Ultimaker is well supported by Marlin since two of its primary authors work for Ultimaker. In fact, Ultimaker used to be the default configuration. What special settings do you need for Ultimaker that are not provided here?

**Comment by CCS86** [comment]
Ah, good to know! I couldn't find a list of changes between the master branch and the Ultimaker branch, and haven't had time to try to compare myself.

I've been making Marlin customizations and building / flashing through Arduino for a while now. But the build instructions for the last RC 1.1 I looked at were a little intense.

I'm psyched to try it out though!

**Comment by thinkyhead** [comment]
Closing this old issue, since we'll be migrating the `RC` code here after the 1.1.0 release. If firmware retraction is working in `RCBugFix` then we're also good here. If it's not working there, I'm sure someone will tell us!
